Repository FRONTENDSCHOOL10/mytrippick, pull requests merged in 2024-09, with the labels that each got.

#13 Feature: 헤더 컴포넌트
  index.html
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/favicon.svg
  public/react.svg
  src/assets/svg/logo.svg
  src/components/HamburgerBtn/HamburgerBtn.jsx
  src/components/HamburgerBtn/HamburgerBtn.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/OffCanvas/Offcanvas.jsx
  src/components/OffCanvas/Offcanvas.module.css
  src/layouts/RootLayout.jsx
  src/pages/Home/Home.module.css
  src/pages/Home/index.jsx
  src/stores/useGlobalStore.jsx
  src/styles/_base.css
  src/styles/_theme.css
  src/styles/_utils.css
  src/styles/_variables.css
  src/styles/main.css
  vite.config.js
Labels: 🎨 style, ✨ feature, ⚙ setting

#16 [공통] 스타일 변수 추가 + 헤더 리팩토링 + 푸터 컴포넌트 제작
  src/assets/svg/github.svg
  src/assets/svg/logo.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/layouts/RootLayout.jsx
  src/styles/_base.css
  src/styles/_variables.css
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#17 [공통] 토글 버튼 컴포넌트 구현
  src/assets/svg/bookmarked.svg
  src/assets/svg/liked.svg
  src/assets/svg/unbookmarked.svg
  src/assets/svg/unliked.svg
  src/components/ToggleButton/ToggleBtn.module.css
  src/components/ToggleButton/ToggleButton.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#20 [공통] 버튼 컴포넌트 구현
  src/components/CommonBtn/CommonBtn.jsx
  src/components/CommonBtn/CommonBtn.module.css
Labels: 🎨 style, 🏠 mark up, ✨ feature

#14 공용 input 컴포넌트 구현 및 스타일링 진행
  src/assets/svg/non-visible.svg
  src/assets/svg/visible.svg
  src/components/AppInput/AppInput.jsx
  src/components/AppInput/AppInput.module.css
  src/styles/_variables.css
Labels: 🎨 style, 🏠 mark up, ✨ feature

#26 [공통] 스타일 변수 업데이트 및 화면 UI 최대 넓이, 높이 설정
  src/components/Footer/Footer.module.css
  src/components/HamburgerBtn/HamburgerBtn.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/OffCanvas/Offcanvas.jsx
  src/components/OffCanvas/Offcanvas.module.css
  src/layouts/RootLayout.jsx
  src/pages/Home/Home.module.css
  src/pages/Home/index.jsx
  src/styles/_base.css
  src/styles/_theme.css
  src/styles/_typography.css
  src/styles/_variables.css
  src/styles/main.css
Labels: 🎨 style, ⚒ refactoring

#28 Design: 공통 스타일 변수 업데이트
  src/styles/_typography.css
  src/styles/_variables.css
Labels: 🎨 style

#33 Feat: Menu컴포넌트 작성
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
  src/components/OffCanvas/Offcanvas.jsx
  src/stores/useGlobalStore.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#34 1차 중간점검 피드백 반영
  index.html
  public/apple-touch-icon.png
  public/favicon.ico
  public/icon-192.png
  public/icon-512.png
  public/icon-mask.png
  public/manifest.webmanifest
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/HamburgerBtn/HamburgerBtn.jsx
  src/components/Header/Header.jsx
  src/components/OffCanvas/Offcanvas.jsx
  src/pages/Home/index.jsx
  src/styles/_variables.css
Labels: ⚒ refactoring

#35 1차 중간점검 피드백 반영
  src/components/CommonBtn/CommonBtn.module.css
  src/components/ToggleBtn/ToggleBtn.jsx
Labels: ⚒ refactoring

#38 Design: 메뉴 컴포넌트 변수사용
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
Labels: 🎨 style, ✨ feature

#40 1차 피드백 내용 반영하여 input 컴포넌트 수정
  src/components/AppInput/AppInput.jsx
  src/components/AppInput/AppInput.module.css
Labels: 🎨 style, ⚒ refactoring

#24 카드 컴포넌트 기본 마크업 구현
  public/testUserPic(delete-later).png
  public/testingPic(delete-later).png
  src/assets/svg/marker-fill.svg
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/pages/Home/index.jsx
  src/styles/_base.css
Labels: 🏠 mark up, ✨ feature

#42 ToggleBtn 상태 문제 수정
  src/components/ToggleBtn/ToggleBtn.jsx
  src/stores/useGlobalStore.jsx
Labels: 🐛 bugs

#37 뒤로가기 버튼 컴포넌트
  src/assets/svg/arrow.svg
  src/components/BackBtn/BackBtn.jsx
  src/components/BackBtn/BackBtn.module.css
  src/components/Header/Header.jsx
  src/pages/PostDetail/PostDetail.module.css
  src/pages/PostDetail/index.jsx
  src/router.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#43 헤더 상단 고정 + 스크롤 시 숨김 처리, 메뉴 마크업 + 스타일링 + 트랜지션 수정
  src/components/Footer/Footer.module.css
  src/components/HamburgerBtn/HamburgerBtn.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
  src/components/OffCanvas/Offcanvas.jsx
  src/components/OffCanvas/Offcanvas.module.css
  src/components/ScrollDirectionDetector.jsx
  src/layouts/RootLayout.jsx
  src/stores/useGlobalStore.jsx
  src/styles/_base.css
  src/styles/_variables.css
  src/styles/main.css
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring

#46 Offcanvas 레이아웃 변경 후 포인터 이벤트 오류 개선
  src/components/Menu/Menu.module.css
  src/components/OffCanvas/Offcanvas.module.css
Labels: 🐛 bugs

#47 [공용] 카테고리 버튼 마크업 및 스타일링 진행
  src/components/CategoryBtn/CategoryBtn.module.css
  src/components/CategoryBtn/CategotyBtn.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#49 회원가입 페이지 마크업 및 스타일링 진행
  package.json
  pnpm-lock.yaml
  src/components/AppInput/AppInput.jsx
  src/components/AppInput/AppInput.module.css
  src/components/CategoryBtn/CategoryBtn.module.css
  src/pages/Register/Register.module.css
  src/pages/Register/index.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature, ⚙ setting

#52 Offcanvas 탭포커스 오류 개선
  src/components/OffCanvas/Offcanvas.module.css
Labels: 🐛 bugs

#54 회원가입 페이지 기능 중 유효성검사 기능 추가
  src/components/AppInput/AppInput.jsx
  src/components/AppInput/AppInput.module.css
  src/pages/Register/index.jsx
  src/utils/index.js
  src/utils/testRegExp.js
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#59 회원가입 페이지 데이터 DB 전송 기능 추가
  src/api/CreateDatas.js
  src/pages/Register/index.jsx
Labels: ⚒ refactoring, ✨ feature, 📞 connectServer

#61 Feature/kakao map/ssw
  index.html
  src/assets/svg/marker.svg
  src/assets/svg/search.svg
  src/assets/svg/toggle-list.svg
  src/assets/svg/toggle-map.svg
  src/assets/svg/xbutton.svg
  src/components/AppInput/AppInput2.jsx
  src/components/AppInput/AppInput2.module.css
  src/components/MapContainer/MapContainer.jsx
  src/components/MapContainer/MapContainer.module.css
  src/components/Menu/Menu.jsx
  src/components/SearchAddr.jsx
  src/hooks/useGeolocation.js
  src/pages/MapSearch/index.jsx
  src/router.jsx
Labels: 🏠 mark up, ✨ feature

#62 마이페이지 구현
  src/assets/svg/bookmark.svg
  src/assets/svg/bookmarked.svg
  src/assets/svg/like.svg
  src/assets/svg/liked.svg
  src/assets/svg/settings.svg
  src/assets/svg/unbookmarked.svg
  src/assets/svg/unliked.svg
  src/components/ToggleBtn/ToggleBtn.jsx
  src/components/ToggleBtn/ToggleBtn.module.css
  src/pages/MyPage/LoginModal.jsx
  src/pages/MyPage/LoginModal.module.css
  src/pages/MyPage/MyPage.module.css
  src/pages/MyPage/ProfileBox.jsx
  src/pages/MyPage/ProfileBox.module.css
  src/pages/MyPage/index.jsx
  src/router.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#63 게시물 등록 페이지에 필요한 몇가지 컴포넌트 제작
  src/assets/svg/add-image.svg
  src/components/AppInput/AppInput.module.css
  src/components/AppTextArea/AppTextArea.jsx
  src/components/AppTextArea/AppTextArea.module.css
  src/components/CategoryBtn/CategoryBtn.module.css
  src/pages/PostWrite/PostWrite.module.css
  src/pages/PostWrite/components/CategoryBtnList/CategoryBtnList.module.css
  src/pages/PostWrite/components/CategoryBtnList/CategotyBtnList.jsx
  src/pages/PostWrite/components/UploadImage/UploadImage.jsx
  src/pages/PostWrite/components/UploadImage/UploadImage.module.css
  src/pages/PostWrite/index.jsx
  src/router.jsx
  src/stores/usePostPhotoFileStore.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#66 Feature/login/ssw
  src/api/submitLogin.js
  src/components/Menu/Menu.module.css
  src/pages/Login/Login.module.css
  src/pages/Login/index.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#68 게시글 상세 페이지 마크업 + 스타일링
  src/assets/svg/dots.svg
  src/assets/svg/filledMarker.svg
  src/assets/svg/plus.svg
  src/components/CommonBtn/CommonBtn.module.css
  src/components/UserProfile/UserProfile.module.css
  src/pages/MyPage/MyPage.module.css
  src/pages/MyPage/ProfileBox.jsx
  src/pages/MyPage/index.jsx
  src/pages/PostDetail/MoreBtn.jsx
  src/pages/PostDetail/MoreBtn.module.css
  src/pages/PostDetail/PostDetail.module.css
  src/pages/PostDetail/ReviewMoreBtn.jsx
  src/pages/PostDetail/ReviewMoreBtn.module.css
  src/pages/PostDetail/index.jsx
Labels: 🎨 style, 🏠 mark up

#71 메인페이지, 카드 컴포넌트 pb 연동
  src/App.jsx
  src/api/likeApi.js
  src/assets/svg/chevron.svg
  src/components/AppInput/AppInput2.jsx
  src/components/AppInput/AppInput2.module.css
  src/components/BackBtn/BackBtn.module.css
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/Menu/Menu.module.css
  src/components/ToggleBtn/ToggleBtn.jsx
  src/components/ToggleBtn/ToggleBtn.module.css
  src/hooks/useLikes.js
  src/pages/Home/Home.module.css
  src/pages/Home/index.jsx
  src/pages/Ranking/Ranking.module.css
  src/pages/Ranking/index.jsx
  src/stores/useLikeStore.jsx
  src/styles/_typography.css
Labels: 🐛 bugs, 🎨 style, ⚒ refactoring, ✨ feature

#75 스크롤감지 함수 종속성 추가
  src/components/ScrollDirectionDetector.jsx
Labels: ⚒ refactoring

#76 게시물 작성 페이지 중 장소 검색 모달 마크업 및 스타일링
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.module.css
  src/pages/PostWrite/index.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#79 react-spinners 패키지 설치 및 로딩 스피너 제작
  package.json
  pnpm-lock.yaml
  src/components/AppSpinner/AppSpinner.jsx
  src/components/AppSpinner/AppSpinner.module.css
Labels: 🎨 style, 🏠 mark up, ✨ feature

#80 랭킹 페이지 마크업+스타일링 / 메인, 랭킹 페이지 lazy 설정 및 데이터 로딩 중 AppSpinner 적용 / 더미 파일 삭제
  dummyfile.txt
  src/components/AppSpinner/AppSpinner.jsx
  src/components/AppSpinner/AppSpinner.module.css
  src/components/Menu/Menu.jsx
  src/data/dummyData.json
  src/pages/Home/Home.module.css
  src/pages/Home/HomeContents.jsx
  src/pages/Home/HomeContents.module.css
  src/pages/Home/index.jsx
  src/pages/Ranking/RankContents.jsx
  src/pages/Ranking/RankContents.module.css
  src/pages/Ranking/Ranking.module.css
  src/pages/Ranking/index.jsx
  src/router.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#82 장소 선택 모달창 구현
  src/components/AppInput/AppInput.jsx
  src/components/AppTextArea/AppTextArea.jsx
  src/pages/PostWrite/PostWrite.module.css
  src/pages/PostWrite/components/CategoryBtnList/CategotyBtnList.jsx
  src/pages/PostWrite/components/DataInput/DateInput.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.module.css
  src/pages/PostWrite/components/UploadImage/UploadImage.jsx
  src/pages/PostWrite/index.jsx
  src/stores/usePlaceDataStore.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#84 게시글 작성 서버 전송 기능 추가 및 기타 기능 추가
  src/components/CategoryBtn/CategotyBtn.jsx
  src/pages/PostWrite/components/CategoryBtnList/CategotyBtnList.jsx
  src/pages/PostWrite/components/DataInput/DateInput.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.module.css
  src/pages/PostWrite/index.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature, 📞 connectServer

#86 회원정보 수정에 필요한 컴포넌트 마크업 & 스타일링 및 회원정보 수정 마크업 & 스타일링 그리고 사용자 프로필 미리보기 로직 구현
  src/assets/svg/camera.svg
  src/assets/svg/default-user.svg
  src/components/AppInput/AppInput.jsx
  src/components/AppTextArea/AppTextArea.module.css
  src/pages/EditUserInfo/EditUserInfo.module.css
  src/pages/EditUserInfo/components/ChangeUserProfilePic/ChangeUserProfilePic.jsx
  src/pages/EditUserInfo/components/ChangeUserProfilePic/ChangeUserProfilePic.module.css
  src/pages/EditUserInfo/components/PasswordAccordion/PasswordAccordion.jsx
  src/pages/EditUserInfo/components/PasswordAccordion/PasswordAccordion.module.css
  src/pages/EditUserInfo/index.jsx
  src/pages/Register/index.jsx
  src/pages/pageTemplate.jsx
  src/router.jsx
  src/stores/usePostPhotoFileStore.jsx
  src/utils/testRegExp.js
Labels: 🎨 style, 🏠 mark up, ✨ feature, 📞 connectServer

#87 react-query 라이브러리 설치, Home 컨텐츠 컴포넌트화, 좋아요 기능 구현 및 pb 연동, Card 컴포넌트 html 문법 검사 오류 개선, 웹접근성 개선, 더미 파일 삭제
  package.json
  pnpm-lock.yaml
  public/testUserPic(delete-later).png
  public/testingPic(delete-later).png
  src/api/likeApi.js
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/LikesHandler.jsx
  src/components/ToggleBtn/ToggleBtn.jsx
  src/components/ToggleBtn/ToggleBtn.module.css
  src/hooks/useLikes.js
  src/layouts/RootLayout.jsx
  src/pages/Home/HomeContents.jsx
  src/pages/Home/components/PostList.jsx
  src/pages/Home/components/RankList.jsx
  src/pages/MyPage/ProfileBox.jsx
  src/pages/Ranking/RankContents.jsx
  src/stores/useGlobalStore.jsx
  src/stores/useHomeStore.jsx
  src/stores/useLikeStore.jsx
Labels: 🐛 bugs, 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#91 Feature/kakao map/ssw
  index.html
  src/api/getDistance.js
  src/api/submitLogin.js
  src/components/AppInput/AppInput2.jsx
  src/components/MapContainer/MapContainer.jsx
  src/components/MapContainer/Modal.jsx
  src/components/MapContainer/Modal.module.css
  src/pages/Login/index.jsx
Labels: 🏠 mark up, ✨ feature

#94 홈 페이지 카테고리 버튼 스와이퍼 적용 및 불필요 코드 정리
  src/components/CategoryBtn/CategoryBtn.module.css
  src/pages/Home/components/CardList/CardList.module.css
  src/pages/Home/components/CardList/PostList.jsx
  src/pages/Home/components/CardList/RankList.jsx
  src/pages/Home/components/CategoryTab/CategoryTab.jsx
  src/pages/Home/components/CategoryTab/CategoryTab.module.css
  src/pages/Home/index.jsx
  src/pages/Ranking/RankContents.jsx
  src/pages/Ranking/RankContents.module.css
  src/pages/Ranking/Ranking.module.css
  src/pages/Ranking/index.jsx
Labels: 🎨 style, ⚒ refactoring, ✨ feature

#97 Feature/curation/ssw
  src/api/submitLogin.js
  src/components/Menu/Menu.jsx
  src/pages/Curation/Curation.module.css
  src/pages/Curation/Login.module.css
  src/pages/Curation/index.jsx
  src/router.jsx
  src/stores/useGlobalStore.jsx
Labels: ✨ feature

#89 게시글 상세 페이지 작성
  src/pages/MyPage/index.jsx
  src/pages/PostDetail/MoreBtn.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/PostDetail/PostDetail.module.css
  src/pages/PostDetail/ReviewMoreBtn.jsx
  src/pages/PostDetail/ReviewMoreBtn.module.css
  src/pages/PostDetail/components/Comment.jsx
  src/pages/PostDetail/components/Comment.module.css
  src/pages/PostDetail/components/MoreBtn.jsx
  src/pages/PostDetail/components/MoreBtn.module.css
  src/pages/PostDetail/components/PostText.jsx
  src/pages/PostDetail/components/PostText.module.css
  src/pages/PostDetail/index.jsx
  src/router.jsx
  src/stores/useGlobalStore.jsx
  src/utils/elapsedTime.js
Labels: ✨ feature

#98 수정한 회원 정보 서버로 전달 및 기타 추가 내용 작성
  public/default-profile.jpg
  src/pages/EditUserInfo/components/PasswordAccordion/PasswordAccordion.jsx
  src/pages/EditUserInfo/index.jsx
  src/stores/useEditPasswordStore.jsx
Labels: ⚒ refactoring, ✨ feature, 📞 connectServer

#101 [공통] 모달 컴포넌트 스타일링 + 경우의 수 고려한 기능 구현 및 홈/랭킹/메뉴에 모달 컴포넌트 적용
  public/default-profile.jpg
  src/components/BasicTextModal/BasicTextModal.jsx
  src/components/BasicTextModal/BasicTextModal.module.css
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
  src/components/ToggleBtn/ToggleBtn.jsx
  src/pages/Home/index.jsx
  src/pages/Ranking/index.jsx
  src/stores/useModalStore.jsx
  src/styles/_base.css
  src/utils/formatTextWithBreaks.js
  src/utils/index.js
Labels: 🎨 style, ⚒ refactoring, ✨ feature

#102 로컬스토리지 get하는 함수 추가와 LinkBtn 컴포넌트 작성 그리고 추가 내용 작성
  src/components/AppInput/AppInputWithValue.jsx
  src/components/LinkBtn/LinkBtn.jsx
  src/components/LinkBtn/LinkBtn.module.css
  src/pages/EditUserInfo/EditUserInfo.module.css
  src/pages/EditUserInfo/index.jsx
  src/pages/PostWrite/index.jsx
  src/utils/getLocalStorage.js
  src/utils/index.js
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature, 📞 connectServer

#105 2차 피드백 내용 중 @esline/compact 설치 및 적용
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/pages/EditUserInfo/index.jsx
Labels: ⚙ setting

#106 AppHelmet 컴포넌트 작성 및 lint 수정 사항 수정
  src/components/AppHelmet/AppHelmet.jsx
  src/pages/EditUserInfo/index.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.jsx
  src/pages/PostWrite/index.jsx
  src/pages/Register/index.jsx
Labels: 🏠 mark up, ⚒ refactoring, ✨ feature

#110 Feature/curation/ssw
  src/pages/Curation/index.jsx
  src/pages/Login/index.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#111 Feature/kakao map/ssw
  src/components/MapContainer/MapContainer.jsx
  src/components/MapContainer/MapContainer.module.css
  src/components/MapContainer/Modal.jsx
  src/components/MapContainer/Modal.module.css
  src/pages/Curation/index.jsx
  src/pages/Login/index.jsx
  src/pages/MapSearch/index.jsx
Labels: 🎨 style, ✨ feature

#108 인기 여행지 API 호출 로직 수정 / 롤업 옵션을 사용한 파일 용량 성능 개선 / 불필요한 파일 및 코드 삭제
  package.json
  src/api/pb.js
  src/components/Card/Card.jsx
  src/components/LikesHandler.jsx
  src/layouts/RootLayout.jsx
  src/pages/Home/components/CardList/PostList.jsx
  src/pages/Home/components/CardList/RankList.jsx
  src/pages/Home/index.jsx
  src/pages/Ranking/index.jsx
  vite.config.js
Labels: 🐛 bugs, ⚒ refactoring, 🌏 deploy

#112 각각 페이지 모달 적용 및 일부 내용 수정
  src/pages/EditUserInfo/index.jsx
  src/pages/PostWrite/components/CategoryBtnList/CategoryBtnList.module.css
  src/pages/PostWrite/components/CategoryBtnList/CategotyBtnList.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.jsx
  src/pages/PostWrite/components/UploadImage/UploadImage.jsx
  src/pages/PostWrite/index.jsx
  src/pages/Register/index.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring

#114 비밀번호 확인 & 회원 탈퇴 페이지 작성
  src/assets/svg/notice.svg
  src/components/Header/Header.jsx
  src/pages/ConfirmPassword/ConfirmPassword.module.css
  src/pages/ConfirmPassword/index.jsx
  src/pages/DeleteAccount/DeleteAccount.module.css
  src/pages/DeleteAccount/index.jsx
  src/pages/MyPage/LoginModal.jsx
  src/pages/MyPage/LoginModal.module.css
  src/pages/MyPage/components/ProfileBox/ProfileBox.jsx
  src/pages/MyPage/components/ProfileBox/ProfileBox.module.css
  src/pages/MyPage/index.jsx
  src/pages/PostDetail/PostDetail.jsx
  src/pages/PostDetail/components/Comment/Comment.jsx
  src/pages/PostDetail/components/Comment/Comment.module.css
  src/pages/PostDetail/components/MoreBtn/MoreBtn.jsx
  src/pages/PostDetail/components/MoreBtn/MoreBtn.module.css
  src/pages/PostDetail/components/PostText/PostText.jsx
  src/pages/PostDetail/components/PostText/PostText.module.css
  src/pages/PostDetail/index.jsx
  src/router.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature

#116 Chore: 리다이렉트 파일 추가
  public/_redirects
Labels: 🌏 deploy

#117 Test: 자동배포테스트
  src/pages/Home/components/CardList/RankList.jsx
Labels: 🌏 deploy

#124 좋아요 로직 수정 및 북마트 핸들러 제작
  src/components/BookmarkHandler.jsx
  src/components/Card/Card.jsx
  src/components/LikesHandler.jsx
  src/layouts/RootLayout.jsx
  src/pages/Home/components/CardList/PostList.jsx
  src/pages/Ranking/index.jsx
Labels: ⚒ refactoring, ✨ feature

#125 게시글 수정 페이지 작성 완료
  src/components/AppTextArea/AppTextAreaWithValue.jsx
  src/components/AppTextArea/AppTextAreaWithValue.module.css
  src/components/CategoryBtn/CategotyBtn.jsx
  src/components/DataInput/DateInput.jsx
  src/components/DataInput/DateInput.module.css
  src/components/UploadImage/UploadImage.jsx
  src/components/UploadImage/UploadImage.module.css
  src/pages/PostEdit/PostEdit.module.css
  src/pages/PostEdit/components/CategoryList.module.css
  src/pages/PostEdit/components/CategotyList.jsx
  src/pages/PostEdit/index.jsx
  src/pages/PostWrite/index.jsx
  src/router.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, ✨ feature, 📞 connectServer

#127 북마크 핸들러 제작 및 큐레이션 페이지 기능 구현
  src/components/BookmarkHandler.jsx
  src/components/LikesHandler.jsx
  src/components/ToggleBtn/ToggleBtn.module.css
  src/pages/Curation/Curation.module.css
  src/pages/Curation/index.jsx
  src/pages/Home/components/CardList/PostList.jsx
  src/stores/useGlobalStore.jsx
Labels: ⚒ refactoring, ✨ feature

#131 토글 버튼 활성화 오류 수정 / postCard 클래스 구분 로직 구현 / Map 모달 postCard 북마크 기능 구현 및 스타일링 수정
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/MapContainer/Modal.jsx
  src/components/MapContainer/Modal.module.css
  src/components/ToggleBtn/ToggleBtn.module.css
Labels: 🎨 style, ⚒ refactoring, ✨ feature

#134 랭킹 페이지 헬멧 컴포넌트 적용 / 큐레이션 테스트 코드 주석 처리 / Menu, Offcanvas ESlint 경고 해결 / input 컴포넌트 ios 오류 해결 / inputCaption 공통 변수 추가 / input svg 스타일 수정
  src/assets/svg/non-visible.svg
  src/assets/svg/visible.svg
  src/components/AppInput/AppInput.module.css
  src/components/AppInput/AppInput2.jsx
  src/components/AppInput/AppInput2.module.css
  src/components/AppInput/AppInputWithValue.module.css
  src/components/AppTextArea/AppTextArea.module.css
  src/components/CategoryBtn/CategoryBtn.module.css
  src/components/DataInput/DateInput.module.css
  src/components/Menu/Menu.jsx
  src/components/OffCanvas/Offcanvas.jsx
  src/pages/Curation/index.jsx
  src/pages/PostWrite/components/PlaceSearchModal/PlaceSearchModal.module.css
  src/pages/PostWrite/index.jsx
  src/pages/Ranking/index.jsx
  src/styles/_typography.css
Labels: 🐛 bugs, 🎨 style, ⚒ refactoring

#135 게시글 상세 페이지 기능 수정
  src/pages/EditUserInfo/index.jsx
  src/pages/MyPage/index.jsx
  src/pages/PostDetail/components/Comment/Comment.jsx
  src/pages/PostDetail/components/MoreBtn/MoreBtn.jsx
  src/pages/PostDetail/components/PostText/PostText.jsx
  src/pages/PostDetail/index.jsx
Labels: 🐛 bugs, ⚒ refactoring

#128 비밀번호 변경 페이지 구현
  src/pages/EditPassword/EditPassword.module.css
  src/pages/EditPassword/index.jsx
  src/pages/EditUserInfo/components/PasswordAccordion/PasswordAccordion.jsx
  src/pages/EditUserInfo/components/PasswordAccordion/PasswordAccordion.module.css
  src/pages/EditUserInfo/index.jsx
  src/router.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature, 📞 connectServer

#139 회원정보 수정 페이지 수정 완료
  src/components/AppInput/AppInputWithValue.module.css
  src/pages/EditUserInfo/index.jsx
Labels: 🎨 style, ⚒ refactoring, 📞 connectServer

#137 큐레이션 페이지 오류 개선
  src/pages/Curation/index.jsx
Labels: 🐛 bugs

#140 Feature/logout/ssw
  src/pages/Register/index.jsx
  src/stores/useGlobalStore.jsx
Labels: ⚒ refactoring, ✨ feature, 📞 connectServer

#141 Feature/kakao map/ssw
  src/api/getDistance.js
  src/components/AppInput/AppInput2.jsx
  src/components/AppInput/PlaceSearch.jsx
  src/components/AppInput/PlaceSearch.module.css
  src/components/MapContainer/MapContainer.jsx
  src/components/MapContainer/MapContainer.module.css
Labels: 🎨 style, ✨ feature

#145 refactor: 오류 해결 및 리팩토링
  src/pages/ConfirmPassword/ConfirmPassword.module.css
  src/pages/ConfirmPassword/index.jsx
  src/pages/DeleteAccount/DeleteAccount.module.css
  src/pages/DeleteAccount/index.jsx
  src/pages/PostDetail/components/Comment/Comment.jsx
  src/pages/PostDetail/index.jsx
Labels: 🐛 bugs, ⚒ refactoring

#143 Feat: 북마크한 게시글 없을 때 큐레이션 페이지 변경
  src/pages/Curation/Curation.module.css
  src/pages/Curation/index.jsx
Labels: 🎨 style, 🏠 mark up, ✨ feature

#147 기타 수정사항 변경
  package.json
  public/default_user.webp
  src/pages/Curation/index.jsx
  src/pages/EditPassword/index.jsx
  src/pages/EditUserInfo/index.jsx
  src/pages/Login/index.jsx
  src/pages/MapSearch/index.jsx
  src/pages/PostEdit/index.jsx
  src/pages/PostWrite/index.jsx
  src/pages/Ranking/index.jsx
  src/pages/Register/index.jsx
Labels: 🐛 bugs, 🏠 mark up

#150 내 주변 여행지 찾기 페이지 지도/리스트 토글 버튼 스타일 수정
  src/components/MapContainer/MapContainer.module.css
Labels: 🎨 style

#152 style: 댓글 스타일 수정
  src/pages/PostDetail/components/Comment/Comment.module.css
Labels: 🎨 style

#153 회원가입 시 기본 프로필 사진 업로드
  src/pages/Register/index.jsx
  src/utils/fetchUserDefaultImg.js
  src/utils/index.js
Labels: ⚒ refactoring, 📞 connectServer

#155 회원 수정 페이지 일부 마크업 및 기타 내용 변경
  src/assets/svg/default-user.svg
  src/pages/EditUserInfo/components/ChangeUserProfilePic/ChangeUserProfilePic.jsx
  src/pages/EditUserInfo/components/ChangeUserProfilePic/ChangeUserProfilePic.module.css
  src/pages/EditUserInfo/index.jsx
Labels: 🎨 style, 🏠 mark up, ⚒ refactoring, 📞 connectServer

#156 Style: 지도-리스트 페이지 푸터 넘어가는 문제 수정
  src/components/MapContainer/MapContainer.jsx
  src/components/MapContainer/MapContainer.module.css
Labels: 🎨 style, 🏠 mark up

#159 리드미 기본 틀
  README.md
Labels: 📖 docs

#162 docs: README.md 작성
  README.md
Labels: 📖 docs

#161 개발 환경 배지 설정
  README.md
Labels: 📖 docs

#164 docs: README.md 추가 작성
  README.md
Labels: 📖 docs

#165 리드미 추가 수정
  README.md
Labels: 📖 docs

#166 리드미 추가 수정
  README.md
Labels: 📖 docs
